Restore versions in the build plugins
These versions numbers were removed in 236b20e and caused an error
during publication:

    $ meteor publish
    => Errors while publishing:

    While publishing the package:
    error: You must specify a version constraint for package blaze
    error: You must specify a version constraint for package underscore
    error: You must specify a version constraint for package htmljs
    error: You must specify a version constraint for package minifiers
    error: You must specify a version constraint for package spacebars-compiler

Note that the dependency version that will actually get includes will
be higher that the one we specified thanks to the Meteor constraints
solver.